model: ResNetSE34L
log_input: True
encoder_type: SAP
trainfunc: subConLoss
batch_size: 64
experiment_name: ResNetSE34L_SSL
save_path: ./save/ResNetSE34L_SSL
train_path: ./data/cnceleb/data
train_list: ./data/train_list_cnceleb.txt
test_path: data/cnceleb/eval
test_list: data/test_list_cnceleb.txt