model: ResNetSE34L
initial_model: "./pre_trained/ResNetSE34L.model"
log_input: True
encoder_type: SAP
nClasses: 5994
scale: 30
margin: 0.3
eval_frames: 400
sup_loss: angleproto
nPerSpeaker: 2
batch_size: 200
